# Site settings
title: Gina Jihyeon Lee
email: gina3833@kaist.ac.kr
description: > # this means to ignore newlines until "baseurl:"
  Passionate AI researcher and sensible women.
description1: Welcome to my website. I mainly share my research outputs including CV and projects. To know more about my real life, Please feel free to read more about me.
baseurl: ""
url: "https://ginajihyeonlee.github.io/"
theme-path: theme-assets # path to header assets etc
map-api-key: AIzaSyB3U7uwIvCyq01orxppAIC1v73y-FBGygY
sass:
  sass_dir: _sass
  style: compressed

collections:
  case:
    output: true
    permalink: /case-studies/:path/
  resource:
    output: true
    permalink: /resources/:path/

# Build settings
markdown: kramdown